spring.application.name=ebank-backend

spring.datasource.url=jdbc:mysql://localhost:3306/ega_bank_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=inf
spring.datasource.password=ck11;1b*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#  CONFIGURATION MAILPIT ( in est en local :le serveur mail est sur localhost:1025 )
spring.mail.host=localhost
spring.mail.port=1025
# Laisse vide, Mailpit n'en a pas besoin en local
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# je ne l'utilise pas pour le moment --
## Configuration Mailtrap
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=587
#spring.mail.username=cf7575e5f78844
#spring.mail.password=f14a0c55f2fe50
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.com.akoueteakue.scolaire.controller.evaluation.EvaluationController=DEBUG

